## This workflow will build and deploy docker image into sherwin artifactory i.e https://artifactory.sherwin.com. 
## Before committing the workflow file update the runs-on to our "sw-" self-hosted runners
name: dockerimagepublish-artifactory
on: 
  [workflow_dispatch, push]
jobs:
  job:
    runs-on: sw-ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Remove Docker Context for buildx
        continue-on-error: true
        id: remove-buildx-context
        run: |
          docker context rm -f builder
     
      - name: setup docker context for buildx
        continue-on-error: true
        id: buildx-context
        run: |
          docker context create builders
          
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
          driver-opts: image=docker.artifactory.sherwin.com/moby/sw_buildkit:1

      - name: Log in to artifactory Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_API_KEY }}
    
      - name: convert reponame to lowercase
        id: lowercasereponame
        run: |
          repoName=`echo "${{github.repository}}" | tr '[:upper:]' '[:lower:]'`
          echo "::set-output name=git_repo_name::${repoName}"
    
      - name: Build and publish container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{secrets.ARTIFACTORY_REGISTRY}}/${{ steps.lowercasereponame.outputs.git_repo_name }}:${{ github.RUN_NUMBER }}
            ${{secrets.ARTIFACTORY_REGISTRY}}/${{ steps.lowercasereponame.outputs.git_repo_name }}:latest
