## This workflow will build and deploy docker image into sherwin artifactory i.e https://artifactory.sherwin.com. 
name: dockerimagepublish-artifactory
on: 
  [workflow_dispatch, push]
jobs:
  job:
    runs-on: sw-ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - uses: sherwin-williams-co/sw-build-deploy-docker-image-composite-action@main
      with:
        image_registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
        image_registry_username: ${{ secrets.ARTIFACTORY_USERNAME }}
        image_registry_api_key: ${{ secrets.ARTIFACTORY_API_KEY }}
        # Optional
       # github_token: ${{ github.TOKEN }}
       # dockerfile_path: docker/Dockerfile
       # image_name: image_name/image
       # buildcontext: .
       # docker_build_args: |
         # args1=1
         # args2=2
