## This workflow will build and deploy maven into sherwin artifactory i.e https://artifactory.sherwin.com. 
## Before committing the workflow file update the runs-on to our "sw-" self-hosted runners
name: Deploy Maven artifact to Artifactory

on: workflow_dispatch

jobs:
  build:
    runs-on: sw-ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2
        
      - name: Setup Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{ "id": "artifactory", "url": "https://artifactory.sherwin.com/artifactory/maven-virtual" }]'
          servers: '[{"id": "artifactory","username": "${{secrets.ARTIFACTORY_USERNAME}}","password": "${{secrets.ARTIFACTORY_API_KEY}}"}]'
          plugin_repositories: '[{ "id": "artifactory", "url": "https://artifactory.sherwin.com/artifactory/maven-virtual" }]'
          mirrors: '[{ "mirrorOf":"*", "id": "artifactory", "url": "https://artifactory.sherwin.com/artifactory/maven-virtual" }]'
      
      - name: Build with Maven
        run: mvn -B package deploy --file pom.xml
