name: Deploy Maven Artifact to Artifactory

on:
  workflow_dispatch

jobs:
  build:

    runs-on: sw-ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2
        
      - name: Setup Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{ "id": "artifactory", "url": "https://artifactory.sherwin.com/artifactory/maven-virtual" }]'  
          servers: '[{"id": "artifactory","username": "${env.ARTIFACTORY_USERNAME_REF}","password": "${env.ARTIFACTORY_TOKEN_REF}"}]'
          plugin_repositories: '[{ "id": "artifactory", "url": "https://artifactory.sherwin.com/artifactory/maven-virtual" }]'  
      
      - name: Build with Maven
        env:
          ARTIFACTORY_USERNAME_REF: "stream-github-actions"
          ARTIFACTORY_TOKEN_REF: ${{ secrets.ARTIFACTORY_API_KEY }}
          BUILD_ENV: 'github-actions'
        run: cd maven;mvn -B package --file pom.xml
