name: Publish Maven to Artifactory
on: workflow_dispatch

jobs:
  build-maven:
    runs-on: sw-ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v1
       with:
         java-version: 11
         
     - name: Build with Maven
       run: mvn -B package
       env:
         ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
         ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
    
    
