name: Rancher Deploy
on: workflow_dispatch
jobs:
  deploy:
    name: rancher deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Read labels file contents
      id: read_label
      uses: andstor/file-reader-action@v1
      with:
        path: "kubernetes/labels"
    - name: File contents
      run: echo "${{ steps.read_label.outputs.contents }}"
    - name: Replace labels
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "@LABELS" 
        replace: ${{ steps.read_label.outputs.contents }}
        include: 'kubernetes/deployment.yml'
    - name: Replace Image Tag
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "@IMAGE_TAG" 
        replace: ${{ github.event.inputs.image_tag }}
        include: 'kubernetes/deployment.yml'
    - name: deploy to cluster
      uses: SW-CORP-IT/sw-rancher-deploy-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_NP_RANCHER }}
      with:
        namespace: "${GITHUB_REF##*/}-gitactions"
        files: "-f kubernetes/."
