name: Rancher Deploy
on: workflow_dispatch
jobs:
  deploy:
    name: rancher deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: SW-CORP-IT/sw-rancher-deploy-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        namespace: "${GITHUB_REF##*/}-gitactions"
        files: "-f kubernetes/."
