## This workflow will build and deploy docker image into sherwin artifactory i.e https://artifactory.sherwin.com for Windows runners. 
## Before committing the workflow file update the runs-on to our "sw-" self-hosted runners
name: Docker Publish (Windows)

on: workflow_dispatch

jobs: 
  docker-artifactory-publish: 
    runs-on: sw-windows-latest 
    steps:
     - uses: actions/checkout@v2
       
     - name: Docker Build and Push
       uses: SW-CORP-IT/sw-windows-docker-build-push@master
       with: 
         registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
         username: ${{ secrets.ARTIFACTORY_USERNAME }}
         password: ${{ secrets.ARTIFACTORY_API_KEY }}
         image: sw-corp-it/rxa313-windows-test
         tags: latest
